work_dir: /bak_home/songcl/3D_visual_grounding/CFNet_paper_checkpoints
train:
  seed: 1999
  epochs: 50
  interval: 1
  pretrain: /bak_home/songcl/3D_visual_grounding/data/ipdn_data/data/sp_unet_backbone.pth
  save_epoch: 100
  grad_clip: 0.1

test:
  seed: 1999
  test_topk_per_scene: 100
  test_score_thresh: 0.0
  test_npoint_thresh: 100

dataloader:
  train:
    batch_size: 2
    num_workers: 4
    persistent_workers: True
  val:
    batch_size: 1
    num_workers: 2
    persistent_workers: True
  test:
    batch_size: 1
    num_workers: 1
    persistent_workers: True

data:
  train:
    type: scannetv2_sample_graph_edge
    dataset: scanrefer
    data_root: /bak_home/songcl/3D_visual_grounding/data/ipdn_data/data/
    prefix: train
    suffix: .pth
    training: True
    mode: 4
    aug: True
    with_elastic: True
    use_xyz: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 2500000
    max_des_len: 78
    lang_num_max: 4
  val:
    type: scannetv2_sample_graph_edge
    dataset: scanrefer
    data_root: /bak_home/songcl/3D_visual_grounding/data/ipdn_data/data/
    prefix: val
    suffix: .pth
    training: False
    mode: 4
    aug: False
    with_elastic: False
    use_xyz: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 2500000
    max_des_len: 78
    lang_num_max: 32
    # 64

model:
  data_root: /bak_home/songcl/3D_visual_grounding/data/ipdn_data/data/
  input_channel: 6
  blocks: 5
  block_reps: 2
  media: 32
  normalize_before: True
  return_blocks: True
  pool: mean
  infer_mode: sem
  fps_num: 256 # default = 512
  task_type: res
  sampling_module:
    num_proposal: 128 # default = 128
    pc_dim: 256
    lang_dim: 256
    d_model: 256
  dec: 
    num_layer: 6
    d_model: 256
    nhead: 8
    hidden_dim: 1024
    dropout: 0.0
    activation_fn: gelu
    iter_pred: True
    attn_mask: True
    kernel: top1
    global_feat: mean
    lang_att: True
    contrastive_align_loss: True
    num_proposal_fine: 512
    num_proposal_query: [128,64,32,16,8,4]
    num_proposal_query_inst: [128,64,32,16,8,4]
  criterion:
    loss_weight: [1.0, 1.0, 0.5, 5.0, 0.1, 0.1, 0.1, 1.0]
    cost_weight: [1.0, 1.0, 0.1]
    # one_mask: True
    loss_fun: focal
    match_last_layer: True
    layer_differ_weight: True
  test_cfg:
    topk_insts: 100
    score_thr: 0.0
    npoint_thr: 100
  norm_eval: False
  fix_module: [
              'text_encoder',
              # 'input_conv',
              # 'unet',
              # 'output_layer'
              ]

optimizer:
  type: AdamW
  lr: 0.0001
  weight_decay: 0.0005
  paramwise_cfg:
   text_encoder:
     lr_mult: 0.001
   input_conv:
     lr_mult: 0.01
   unet:
     lr_mult: 0.01
   output_layer:
     lr_mult: 0.01
   dec:
     lr_mult: 1.0

lr_scheduler:
  type: PolyLR
  max_iters: 70
  # max_iters: 512
  power: 4.0
  constant_ending: 0.0